// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/accounts": {
    params: {};
  };
  "/ui-layers": {
    params: {};
  };
  "/websites": {
    params: {};
  };
  "/customizations": {
    params: {};
  };
  "/usage": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/api-usage": {
    params: {};
  };
  "/api-keys": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/changelog": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/accounts" | "/ui-layers" | "/websites" | "/customizations" | "/usage" | "/docs" | "/api-usage" | "/api-keys" | "/profile" | "/changelog" | "/settings" | "/login" | "/register" | "/forgot-password" | "/reset-password";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/accounts.tsx": {
    id: "routes/accounts";
    page: "/accounts";
  };
  "routes/ui-layers.tsx": {
    id: "routes/ui-layers";
    page: "/ui-layers";
  };
  "routes/websites.tsx": {
    id: "routes/websites";
    page: "/websites";
  };
  "routes/customizations.tsx": {
    id: "routes/customizations";
    page: "/customizations";
  };
  "routes/usage.tsx": {
    id: "routes/usage";
    page: "/usage";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs";
  };
  "routes/api-usage.tsx": {
    id: "routes/api-usage";
    page: "/api-usage";
  };
  "routes/api-keys.tsx": {
    id: "routes/api-keys";
    page: "/api-keys";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/changelog.tsx": {
    id: "routes/changelog";
    page: "/changelog";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/accounts": typeof import("./app/routes/accounts.tsx");
  "routes/ui-layers": typeof import("./app/routes/ui-layers.tsx");
  "routes/websites": typeof import("./app/routes/websites.tsx");
  "routes/customizations": typeof import("./app/routes/customizations.tsx");
  "routes/usage": typeof import("./app/routes/usage.tsx");
  "routes/docs": typeof import("./app/routes/docs.tsx");
  "routes/api-usage": typeof import("./app/routes/api-usage.tsx");
  "routes/api-keys": typeof import("./app/routes/api-keys.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/changelog": typeof import("./app/routes/changelog.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.tsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.tsx");
};