package handlers

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"api.kuttl.xyz/internal/middleware"
	"api.kuttl.xyz/pkg/response"
	"github.com/google/uuid"
	"github.com/gorilla/mux"
)

type WebsitesHandler struct {
	db *sql.DB
}

func NewWebsitesHandler(db *sql.DB) *WebsitesHandler {
	return &WebsitesHandler{db: db}
}

type Website struct {
	ID             string     `json:"id" db:"id"`
	UserID         string     `json:"user_id" db:"user_id"`
	Name           string     `json:"name" db:"name"`
	URL            string     `json:"url" db:"url"`
	Description    *string    `json:"description" db:"description"`
	HashKey        string     `json:"hash_key" db:"hash_key"`
	IsActive       bool       `json:"is_active" db:"is_active"`
	CreatedAt      time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at" db:"updated_at"`
	LastRequestAt  *time.Time `json:"last_request_at" db:"last_request_at"`
	TotalRequests  int        `json:"total_requests" db:"total_requests"`
}

type CreateWebsiteRequest struct {
	Name        string  `json:"name" validate:"required,max=255"`
	URL         string  `json:"url" validate:"required,url"`
	Description *string `json:"description,omitempty"`
}

type UpdateWebsiteRequest struct {
	Name        *string `json:"name,omitempty" validate:"omitempty,max=255"`
	URL         *string `json:"url,omitempty" validate:"omitempty,url"`
	Description *string `json:"description,omitempty"`
	IsActive    *bool   `json:"is_active,omitempty"`
}

// ListWebsites returns all websites for the authenticated user
func (h *WebsitesHandler) ListWebsites(w http.ResponseWriter, r *http.Request) {
	user := middleware.GetUserFromContext(r.Context())
	if user == nil {
		response.Error(w, http.StatusUnauthorized, "Authentication required")
		return
	}

	query := `
		SELECT id, user_id, name, url, description, hash_key, is_active, 
			   created_at, updated_at, last_request_at, total_requests
		FROM websites 
		WHERE user_id = $1 
		ORDER BY created_at DESC
	`

	rows, err := h.db.Query(query, user.ID)
	if err != nil {
		response.Error(w, http.StatusInternalServerError, "Failed to fetch websites")
		return
	}
	defer rows.Close()

	var websites []Website
	for rows.Next() {
		var website Website
		err := rows.Scan(
			&website.ID, &website.UserID, &website.Name, &website.URL,
			&website.Description, &website.HashKey, &website.IsActive,
			&website.CreatedAt, &website.UpdatedAt, &website.LastRequestAt,
			&website.TotalRequests,
		)
		if err != nil {
			response.Error(w, http.StatusInternalServerError, "Failed to parse website data")
			return
		}
		websites = append(websites, website)
	}

	if websites == nil {
		websites = []Website{}
	}

	response.JSON(w, http.StatusOK, map[string]interface{}{
		"success": true,
		"data":    websites,
	})
}

// CreateWebsite creates a new website with a unique hash key
func (h *WebsitesHandler) CreateWebsite(w http.ResponseWriter, r *http.Request) {
	user := middleware.GetUserFromContext(r.Context())
	if user == nil {
		response.Error(w, http.StatusUnauthorized, "Authentication required")
		return
	}

	var req CreateWebsiteRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		response.Error(w, http.StatusBadRequest, "Invalid JSON")
		return
	}

	// Validate required fields
	if req.Name == "" || req.URL == "" {
		response.Error(w, http.StatusBadRequest, "Name and URL are required")
		return
	}

	// Check if user already has a website with this name
	var existingCount int
	err := h.db.QueryRow(`
		SELECT COUNT(*) FROM websites 
		WHERE user_id = $1 AND name = $2
	`, user.ID, req.Name).Scan(&existingCount)

	if err != nil {
		response.Error(w, http.StatusInternalServerError, "Failed to validate website name")
		return
	}

	if existingCount > 0 {
		response.Error(w, http.StatusConflict, "You already have a website with this name")
		return
	}

	websiteID := uuid.New().String()

	// Insert new website (hash key will be generated by database function)
	query := `
		INSERT INTO websites (id, user_id, name, url, description, hash_key)
		VALUES ($1, $2, $3, $4, $5, generate_website_hash_key())
		RETURNING hash_key, created_at
	`

	var hashKey string
	var createdAt time.Time
	err = h.db.QueryRow(query, websiteID, user.ID, req.Name, req.URL, req.Description).
		Scan(&hashKey, &createdAt)

	if err != nil {
		if err.Error() == `pq: duplicate key value violates constraint "unique_user_website_name"` {
			response.Error(w, http.StatusConflict, "You already have a website with this name")
			return
		}
		response.Error(w, http.StatusInternalServerError, "Failed to create website")
		return
	}

	// Return the created website
	website := Website{
		ID:            websiteID,
		UserID:        user.ID.String(),
		Name:          req.Name,
		URL:           req.URL,
		Description:   req.Description,
		HashKey:       hashKey,
		IsActive:      true,
		CreatedAt:     createdAt,
		UpdatedAt:     createdAt,
		TotalRequests: 0,
	}

	response.JSON(w, http.StatusCreated, map[string]interface{}{
		"success": true,
		"data":    website,
	})
}

// GetWebsite returns a specific website by ID
func (h *WebsitesHandler) GetWebsite(w http.ResponseWriter, r *http.Request) {
	user := middleware.GetUserFromContext(r.Context())
	if user == nil {
		response.Error(w, http.StatusUnauthorized, "Authentication required")
		return
	}

	vars := mux.Vars(r)
	websiteID := vars["id"]

	var website Website
	query := `
		SELECT id, user_id, name, url, description, hash_key, is_active, 
			   created_at, updated_at, last_request_at, total_requests
		FROM websites 
		WHERE id = $1 AND user_id = $2
	`

	err := h.db.QueryRow(query, websiteID, user.ID).Scan(
		&website.ID, &website.UserID, &website.Name, &website.URL,
		&website.Description, &website.HashKey, &website.IsActive,
		&website.CreatedAt, &website.UpdatedAt, &website.LastRequestAt,
		&website.TotalRequests,
	)

	if err == sql.ErrNoRows {
		response.Error(w, http.StatusNotFound, "Website not found")
		return
	}

	if err != nil {
		response.Error(w, http.StatusInternalServerError, "Failed to fetch website")
		return
	}

	response.JSON(w, http.StatusOK, map[string]interface{}{
		"success": true,
		"data":    website,
	})
}

// UpdateWebsite updates a website's properties
func (h *WebsitesHandler) UpdateWebsite(w http.ResponseWriter, r *http.Request) {
	user := middleware.GetUserFromContext(r.Context())
	if user == nil {
		response.Error(w, http.StatusUnauthorized, "Authentication required")
		return
	}

	vars := mux.Vars(r)
	websiteID := vars["id"]

	var req UpdateWebsiteRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		response.Error(w, http.StatusBadRequest, "Invalid JSON")
		return
	}

	// Build dynamic update query
	setParts := []string{}
	args := []interface{}{}
	argIndex := 1

	if req.Name != nil {
		setParts = append(setParts, "name = $"+fmt.Sprintf("%d", argIndex))
		args = append(args, *req.Name)
		argIndex++
	}

	if req.URL != nil {
		setParts = append(setParts, "url = $"+fmt.Sprintf("%d", argIndex))
		args = append(args, *req.URL)
		argIndex++
	}

	if req.Description != nil {
		setParts = append(setParts, "description = $"+fmt.Sprintf("%d", argIndex))
		args = append(args, *req.Description)
		argIndex++
	}

	if req.IsActive != nil {
		setParts = append(setParts, "is_active = $"+fmt.Sprintf("%d", argIndex))
		args = append(args, *req.IsActive)
		argIndex++
	}

	if len(setParts) == 0 {
		response.Error(w, http.StatusBadRequest, "No fields to update")
		return
	}

	// Add WHERE clause parameters
	args = append(args, websiteID, user.ID)

	query := fmt.Sprintf(`
		UPDATE websites 
		SET %s, updated_at = NOW()
		WHERE id = $%d AND user_id = $%d
	`, strings.Join(setParts, ", "), argIndex, argIndex+1)

	result, err := h.db.Exec(query, args...)
	if err != nil {
		response.Error(w, http.StatusInternalServerError, "Failed to update website")
		return
	}

	rowsAffected, _ := result.RowsAffected()
	if rowsAffected == 0 {
		response.Error(w, http.StatusNotFound, "Website not found")
		return
	}

	response.JSON(w, http.StatusOK, map[string]interface{}{
		"success": true,
		"message": "Website updated successfully",
	})
}

// DeleteWebsite deletes a website
func (h *WebsitesHandler) DeleteWebsite(w http.ResponseWriter, r *http.Request) {
	user := middleware.GetUserFromContext(r.Context())
	if user == nil {
		response.Error(w, http.StatusUnauthorized, "Authentication required")
		return
	}

	vars := mux.Vars(r)
	websiteID := vars["id"]

	result, err := h.db.Exec(`
		DELETE FROM websites 
		WHERE id = $1 AND user_id = $2
	`, websiteID, user.ID)

	if err != nil {
		response.Error(w, http.StatusInternalServerError, "Failed to delete website")
		return
	}

	rowsAffected, _ := result.RowsAffected()
	if rowsAffected == 0 {
		response.Error(w, http.StatusNotFound, "Website not found")
		return
	}

	response.JSON(w, http.StatusOK, map[string]interface{}{
		"success": true,
		"message": "Website deleted successfully",
	})
}

// GetWebsiteByHashKey returns website info by hash key (for API usage)
func (h *WebsitesHandler) GetWebsiteByHashKey(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	hashKey := vars["hash_key"]

	var website Website
	query := `
		SELECT id, user_id, name, url, description, hash_key, is_active, 
			   created_at, updated_at, last_request_at, total_requests
		FROM websites 
		WHERE hash_key = $1 AND is_active = TRUE
	`

	err := h.db.QueryRow(query, hashKey).Scan(
		&website.ID, &website.UserID, &website.Name, &website.URL,
		&website.Description, &website.HashKey, &website.IsActive,
		&website.CreatedAt, &website.UpdatedAt, &website.LastRequestAt,
		&website.TotalRequests,
	)

	if err == sql.ErrNoRows {
		response.Error(w, http.StatusNotFound, "Website not found or inactive")
		return
	}

	if err != nil {
		response.Error(w, http.StatusInternalServerError, "Failed to fetch website")
		return
	}

	response.JSON(w, http.StatusOK, map[string]interface{}{
		"success": true,
		"data":    website,
	})
}